app = "defi-qa-frontend"
primary_region = "mia"  # Change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://defi-qa-backend.fly.dev"

# HTTP service configuration for frontend
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

# VM configuration
[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

# Deployment strategy
[deploy]
  strategy = "rolling" 