services:
  - type: web
    name: defi-qa-bot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false

  - type: static
    name: defi-qa-bot-frontend
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: "./frontend/build"
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18 