# fly.toml app configuration file generated for defi-qa-backend-test on 2025-07-11T13:24:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "defi-qa-backend"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  HOST = "0.0.0.0"
  PORT = "8000"
  DEBUG = "false"
  RELOAD = "false"
  ALLOWED_ORIGINS = "https://defi-qa-frontend.fly.dev,https://your-custom-domain.com"
  RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
  RATE_LIMIT_WINDOW_SECONDS = "60"
  AGENT_SIMILARITY_THRESHOLD = "0.6"
  AGENT_MAX_RESULTS = "3"
  AGENT_CACHE_ENABLED = "true"
  AGENT_LLM_MODEL = "gpt-4o-mini"
  AGENT_EMBEDDING_MODEL = "text-embedding-3-small"
  CACHE_DIR = "/app/persistent/cache"
  CACHE_ENABLED = "true"
  LOG_LEVEL = "INFO"
  LOG_DIR = "/app/persistent/logs"
  ENABLE_JSON_LOGS = "true"
  ENABLE_CONSOLE_LOGS = "true"
  MAX_CONCURRENT_REQUESTS = "10"
  MONITORING_ENABLED = "true"
  USE_HTTPS = "false"
  TRUST_PROXY = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"

[[mounts]]
  source = "app_data"
  destination = "/app/persistent"

[deploy]
  strategy = "rolling"
