name: Deploy Backend to Fly.io

on:
  push:
    branches: [ deploy ]
    paths: 
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy Backend to Fly.io
      run: flyctl deploy --remote-only --config backend/fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 