name: Deploy to Fly.io

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend to Fly.io
        run: flyctl deploy --config backend/fly.toml --dockerfile backend/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Frontend to Fly.io
        run: flyctl deploy --config frontend/fly.toml --dockerfile frontend/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    
    steps:
      - name: Check Backend Health
        run: |
          echo "Waiting for backend to be ready..."
          sleep 30
          curl -f https://defi-qa-backend.fly.dev/health || exit 1
          echo "Backend is healthy!"

      - name: Check Frontend Health
        run: |
          echo "Waiting for frontend to be ready..."
          sleep 15
          curl -f https://defi-qa-frontend.fly.dev/ || exit 1
          echo "Frontend is healthy!"

      - name: Deployment Success Notification
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Backend: https://defi-qa-backend.fly.dev"
          echo "Frontend: https://defi-qa-frontend.fly.dev"